name: sql_server

services:
    sql_server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: Pass.Word
          MSSQL_PID: Developer
        ports:
        - 1433:1433
        volumes:
        - type: volume
          source: data
          target: /var/opt/mssql

volumes:
  data: